#!/bin/sh
#
# k2hb       Start/Stop/Restart Kafka-to-Hbase application
#
# chkconfig: 345 70 10
# description: K2HB - Kafka-to-Hbase  \
#              Starts at boot time.
#
### BEGIN INIT INFO
# Provides:          k2hb
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts Kafka-to-Hbase
### END INIT INFO


# Init file for K2HB

# pidfile: /var/run/k2hb.pid
NAME=k2hb
PID_FILE=/var/run/$NAME.pid
PROCESS_USER=k2hb
DAEMON="/opt/k2hb/k2hb.sh"

start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ ! -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$PID_FILE exists, process is already running"
      exit 0
    else
      echo "$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
      rm -f $PID_FILE
      start
    fi
  else
    /sbin/runuser $PROCESS_USER -c "$DAEMON &"
    sleep 2
    PID=`ps ax | grep -E '[k]afka2hbase-.*jar' | awk '{print $1}'`
    echo $PID > $PID_FILE;
    echo "$NAME started"
  fi
}

k2hb_running() {
    jps | grep Kafka2HbaseKt
}


stop() {
  if [ ! -f $PID_FILE ]
  then
    echo "$PID_FILE does not exist, process is not running"
    return 1
  else
      K2HB_PID=$(cat $PID_FILE)
      kill "$K2HB_PID";
      rm -f "$PID_FILE";

      checks=0
      while k2hb_running && [ $checks -lt 120 ]; do
          echo K2HB STILL RUNNING: $checks/120 checks made
          checks=$((checks+1))
          sleep 1
      done

      if k2hb_running; then
          echo FORCEABLY KILLING K2HB
          kill -9 "$K2HB_PID"
      fi

      echo "$NAME stopped"
      return 0
  fi
}

status() {
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$NAME stopped but pid file exists"
      exit 1
    else
      echo "$NAME running with pid $PID"
      exit 0
    fi
  else
    echo "$NAME stopped"
    exit 1
  fi
}
case "$1" in
  status)
    status
	;;
  start)
    echo "Starting daemon: "$NAME
    start
	;;
  stop)
    echo "Stopping daemon: "$NAME
    stop
	;;
  restart)
    echo "Restarting daemon: "$NAME
	stop
    sleep 5
    start
	;;
  *)
	echo "Usage: "$1" {status|start|stop|restart}"
	exit 1
esac
exit 0
