jobs:
  - name: audit-qa
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-qa
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: qa
        - .: (( inject meta.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: qa

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-audit-storage-for-yesterday
        config:
          params:
            CORPORATE_STORAGE_TYPE: "audit"
            DATE_TO_RUN_ON: "yesterday"
