jobs:
  - name: coalesce-manifests-qa
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-qa
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: qa
        - .: (( inject meta.plan.terraform-output-internal-compute ))
          config:
            params:
              TF_WORKSPACE: qa
        - .: (( inject meta.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: qa

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-audit-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            CORPORATE_STORAGE_TYPE: "audit"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-equalities-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            CORPORATE_STORAGE_TYPE: "equalities"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-main-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            CORPORATE_STORAGE_TYPE: "main"
