jobs:
  - name: coalesce-manifests-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-preprod
        - get: utc-1am
          trigger: true
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: preprod
        - .: (( inject meta.plan.terraform-output-internal-compute ))
          config:
            params:
              TF_WORKSPACE: preprod
        - .: (( inject meta.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: preprod

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-audit-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            CORPORATE_STORAGE_TYPE: "audit"
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-equalities-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            CORPORATE_STORAGE_TYPE: "equalities"
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-manifests-task ))
        task: coalesce-main-manifests
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            CORPORATE_STORAGE_TYPE: "main"
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"
