jobs:
  - name: coalesce-integration
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-integration
        - get: utc-1am
          trigger: false
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: integration
        - .: (( inject meta.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: integration

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-audit-storage-for-yesterday
        config:
          params:
            CORPORATE_STORAGE_TYPE: "audit"
            DATE_TO_RUN_ON: "yesterday"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-equalities-storage-for-yesterday
        config:
          params:
            CORPORATE_STORAGE_TYPE: "equalities"
            DATE_TO_RUN_ON: "yesterday"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-main-storage-for-yesterday
        config:
          params:
            CORPORATE_STORAGE_TYPE: "main"
            DATE_TO_RUN_ON: "yesterday"
