jobs:
  - name: coalesce-production
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-production
        - get: utc-1am
          trigger: true
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: production
        - .: (( inject meta.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: production

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-audit-storage-for-yesterday
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            CORPORATE_STORAGE_TYPE: "audit"
            START_DATE: "yesterday"
            THREAD_COUNT: 3
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-equalities-storage-for-yesterday
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            CORPORATE_STORAGE_TYPE: "equalities"
            START_DATE: "yesterday"
            THREAD_COUNT: 3
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"

      - .: (( inject meta-corporate-storage-coalescence.plan.run-coalesce-task ))
        task: coalesce-main-storage-for-yesterday
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            CORPORATE_STORAGE_TYPE: "main"
            START_DATE: "yesterday"
            THREAD_COUNT: 3
            AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT: "true"
