jobs:
  - name: apply-and-test-with-ami
    max_in_flight: 1
    serial_groups: [qa-applies]
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: aws-internal-compute
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: aws-dataworks-e2e-framework
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
          - get: dw-al2-hardened-ami
            resource: untested-dw-al2-jvm-ami
            trigger: true
          - get: dataworks-aws-ingest-consumers
            trigger: true
          - get: k2hb-release
            version:
              tag: ((k2hb_version))
            trigger: true
            passed:
              - mirror-k2hb

      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'

      - in_parallel:
          - .: (( inject meta.plan.terraform-output-ingest ))
            config:
              params:
                TF_WORKSPACE: qa
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            config:
              params:
                TF_WORKSPACE: qa
          - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-output-snapshot-sender ))
            config:
              params:
                TF_WORKSPACE: qa
          - .: (( inject meta.plan.terraform-output-ingest-consumers ))
            config:
              params:
                TF_WORKSPACE: qa

      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.run-behave-job ))
        task: data-streaming-tests
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_FEATURE_TAG_FILTER: "data-streaming"
            DATA_STREAMING_TESTS_SKIP_RECONCILING: "true"

      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.run-behave-job))
        task: end-to-end-tests
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_FEATURE_TAG_FILTER: "end-to-end"

    ensure:
      do:
        - .: (( inject meta-dataworks-aws-ingest-consumers.plan.tear-down ))
          config:
            params:
              AWS_ACC: ((aws_account.qa))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
                
    on_failure:
      do:
        - .: (( inject meta-dataworks-aws-ingest-consumers.plan.ami-test-results ))
          task: ami-test-result-fail
          config:
            params:
              RESULT: FAILED

    on_success:
      do:
        - .: (( inject meta-dataworks-aws-ingest-consumers.plan.ami-test-results ))
          task: ami-test-result-success
          config:
            params:
              RESULT: SUCCESS
