jobs:
  - name: dataworks-aws-ingest-consumers-pr
    plan:
      - get: dataworks-aws-ingest-consumers-pr
        trigger: true
        version: every

      - put: dataworks-aws-ingest-consumers-pr
        params:
          path: dataworks-aws-ingest-consumers-pr
          status: pending

      - get: dw-al2-hardened-ami

      - get: k2hb-release
        version:
          tag: ((k2hb_version))
        passed:
          - mirror-k2hb

      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-ingest-consumers: dataworks-aws-ingest-consumers-pr

      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-ingest-consumers: dataworks-aws-ingest-consumers-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-aws-ingest-consumers-pr
          params:
            path: dataworks-aws-ingest-consumers-pr
            status: failure
        on_success:
          put: dataworks-aws-ingest-consumers-pr
          params:
            path: dataworks-aws-ingest-consumers-pr
            status: success
