jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-internal-compute
            trigger: false
            passed:
              - qa
          - get: aws-ingestion
            trigger: false
            passed:
              - qa
          - get: aws-dataworks-e2e-framework
            trigger: false
            passed:
              - qa
          - get: aws-snapshot-sender
            trigger: false
            passed:
              - qa
          - get: dw-al2-hardened-ami
            trigger: true
            passed:
              - qa
          - get: dataworks-aws-ingest-consumers
            trigger: true
            passed:
              - qa
          - get: k2hb-release
            version:
              tag: ((k2hb_version))
            trigger: true
            passed:
              - qa

      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'
