jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - get: dw-al2-hardened-ami
        trigger: true

      - get: dataworks-aws-ingest-consumers
        trigger: true

      - get: k2hb-release
        version:
          tag: ((k2hb_version))
        trigger: true
        passed:
          - mirror-k2hb

      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
