jobs:
  - name: dataworks-aws-ingest-consumers-pr
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: dw-al2-hardened-ami
          - get: dw-al2-ecs-ami
          - get: k2hb-release
            version:
              tag: ((k2hb_version_qa))
            passed:
              - mirror-k2hb
          - get: k2hb-reconciliation-image
            version:
              digest: ((k2hb_reconciliation_container_version))
            trigger: true
          - get: dataworks-aws-ingest-consumers-pr
            trigger: true
            version: every

      - put: dataworks-aws-ingest-consumers-pr
        params:
          path: dataworks-aws-ingest-consumers-pr
          status: pending

      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-ingest-consumers: dataworks-aws-ingest-consumers-pr

      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-ingest-consumers: dataworks-aws-ingest-consumers-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-aws-ingest-consumers-pr
          params:
            path: dataworks-aws-ingest-consumers-pr
            status: failure
        on_success:
          put: dataworks-aws-ingest-consumers-pr
          params:
            path: dataworks-aws-ingest-consumers-pr
            status: success
