jobs:
  - name: production
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dw-al2-jvm-ami
            trigger: true
            passed:
              - preprod
          - get: dataworks-aws-ingest-consumers
            trigger: true
            passed:
              - preprod
          - get: dw-al2-ecs-ami
            trigger: true
            passed:
              - preprod
          - get: k2hb-release
            version:
              tag: ((k2hb_version_prod))
            trigger: true
            passed:
              - preprod
          - get: k2hb-reconciliation-image
            version:
              digest: ((k2hb_reconciliation_container_version))
            trigger: true
            passed:
              - preprod

      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.terraform-output-ingest-consumers ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.provision-metadata-table-ucfs ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.provision-metadata-table-equalities ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
      - .: (( inject meta-dataworks-aws-ingest-consumers.plan.provision-metadata-table-audit ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
